### PR TITLE
Added Berries and Cherries support (and rimraf)

### PR DESCRIPTION
**Pull request by wavpro**
First of all I added support for the `Five-SeveN | Berries and Cherries`. It's as accurate as I could get it, and is almost the same as [this guide](https://www.reddit.com/r/csgomarketforum/comments/kahu5r/discussion_five_seven_berries_and_cherries_blue/) suggests, and compared with visual inspection of course.

Second, I switched out `rm -rf` for the npm package `rimraf`, as it is supported on all platforms. Previously, if you tried to build the project on windows it'd fail, as the `rm` command doesn't exist on windows.

### CODE REVIEW

**Comment by wavpro** [comment]
Sorry for the @chescos, but could you review this PR?

**Comment by chescos** [comment]
Thanks for your contribution! Sorry for the late reply, been a little busy lately.

Looks interesting, however, the [paintkit config](https://github.com/chescos/csgo-fade-percentage-calculator/blob/026ce5c48d3e05485d18d4614fd2c3deb1e93218/src/modules/BerriesAndCherriesCalculator.ts#L14) looks arbitrary, did you just try out numbers until the output looked somewhat correct?

The thing is, those properties are specified for each skin in the [game files](https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/scripts/items/items_game.txt). For the `Five-SeveN | Berries And Cherries`, the actual config looks like this: 

```
"1002"
{
	"name"		"aa_fade_red_blue"
	"description_string"		"#PaintKit_aa_fade_red_blue"
	"description_tag"		"#PaintKit_aa_fade_red_blue_Tag"
	"style"		"6"
	"pattern"		"fade"
	"color0"		"88 16 16"
	"color1"		"72 16 19"
	"color2"		"15 14 14"
	"color3"		"31 80 136"
	"pattern_scale"		"2.000000"
	"phongexponent"		"34"
	"phongalbedoboost"		"80"
	"ignore_weapon_size_scale"		"1"
	"only_first_material"		"1"
	"pattern_offset_x_start"		"-1.480000"
	"pattern_offset_x_end"		"0.600000"
	"pattern_offset_y_start"		"0.000000"
	"pattern_offset_y_end"		"1.000000"
	"pattern_rotate_start"		"10.000000"
	"pattern_rotate_end"		"20.000000"
	"wear_remap_min"		"0.000000"
	"wear_remap_max"		"0.100000"
}
```

I'm not sure if our algorithm makes sense for this skin though, as it has a variable rotation as well as a variable X and Y axis (Fade skins only have a variable rotation). Theoretically, the output should still be good as the Y axis doesn't seem to matter much and we support the X axis.

Could you update your PR with the correct config values and manually check if the output still makes sense?

**Comment by wavpro** [comment]
> 

No problem, I understand!

You are correct, that was my methodology, kinda. I started off with the values that you mention, from the items_game.txt, and they were completely off-basis, so I experimented by adjusting values slightly one at a time to hone in close to what the consensus is for berries and cherries. 

It is definitely not 100% accurate, and I'd completely understand if you don't accept this PR. I consider it good enough for me, and I'll probably just extend the base class in my own project if it isn't good enough to be included.

**Comment by chescos** [comment]
Ahhh okay, got it!

Sorry but in this case, I prefer not to merge this as the method to achieve the results is too random.

If you want, you can clean this PR up to only include the `rimraf` addition (or open a new one for that) - I'd gladly merge that one. If you don't want to bother with that, just let me know, and I can open a PR for it as well.

**Comment by wavpro** [comment]
> Ahhh okay, got it!
> 
> Sorry but in this case, I prefer not to merge this as the method to achieve the results is too random.
> 
> If you want, you can clean this PR up to only include the `rimraf` addition (or open a new one for that) - I'd gladly merge that one. If you don't want to bother with that, just let me know, and I can open a PR for it as well.

Done!

**Comment by chescos** [comment]
Great, thank you!

**Pull request merged**
